module.exports.Product = require('./Product')
module.exports.User = require('./User')
module.exports.New = require('./New')
module.exports.Category = require('./Category')
module.exports.Order = require('./Order')